### ISSUE TITLE
Disconnect between the documention and code

### ISSUE THREAD

**Issue by smit-shah21** [LoMesh-ORG/LWmesh#77]
- The document states the Network Address should be 8-bit long. But the default network address is  "AAAA" which is 16-bit long.
- The command "AT+RECV" doesn't have a "?" at the end of the command. Should be "AT+RECV?"  in the document.
- "?" lacks in commands "AT+MODE", "AT+RFCH" in the document.

**Comment by sramrajkar** [comment]
Only Network address needed fixing
